# Generated by Django 3.2.7 on 2021-09-19 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=1024)),
                ('passwordusuario', models.CharField(max_length=1024)),
            ],
            managers=[
                ('empAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('idpuja', models.AutoField(primary_key=True, serialize=False)),
                ('valorpuja', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idrequerimiento', models.ForeignKey(db_column='idrequerimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.requerimiento')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Adjudicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProyecto', models.ForeignKey(db_column='idproyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.proyecto')),
                ('idUsuarioGanador', models.ForeignKey(db_column=' idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario')),
            ],
        ),
    ]
