# Generated by Django 3.2.7 on 2021-09-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjudicaciones',
            name='idUsuarioGanador',
        ),
        migrations.AddField(
            model_name='adjudicaciones',
            name='nombreUsuarioGanador',
            field=models.ForeignKey(db_column='nombreusuario', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario'),
            preserve_default=False,
        ),
    ]
