# Generated by Django 3.2.7 on 2021-09-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20210919_1526'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='puja',
            name='valorpuja',
            field=models.FloatField(),
        ),
    ]
